[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "hardhat/=lib/hardhat/packages/hardhat-core/",
]
optimizer = true
optimizer_runs = 200
evm_version = "paris"

[fmt]
line_length = 100
multiline_func_header = "attributes_first"

# Uncomment to configure Basescan verification (optional)
# [etherscan]
# basesepolia = { key = "${BASESCAN_API_KEY}" }

